# Generated by Django 5.2.1 on 2025-08-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eAuction', '0002_alter_register_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
