# Generated by Django 5.2.1 on 2025-08-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eAuction', '0003_alter_register_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='regid',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
