# Generated by Django 5.2.1 on 2025-08-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subcatid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=50)),
                ('subcatname', models.CharField(max_length=50, unique=True)),
                ('subcaticon', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='caticonname',
            new_name='caticon',
        ),
    ]
