# Generated by Django 5.2.1 on 2025-08-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('txnid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
