# Generated by Django 5.2.1 on 2025-08-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('uid', models.CharField(max_length=50)),
                ('bidprice', models.IntegerField()),
                ('info', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('subcatname', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('baseprice', models.IntegerField()),
                ('picon', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=50)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
