# Generated by Django 5.2.1 on 2025-08-27 09:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_bid_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid',
            new_name='bid_id',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bidprice',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='info',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='bid',
            name='uid',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder_email',
            field=models.CharField(default='anonymous@example.com', max_length=100),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder_id',
            field=models.CharField(default='guest', max_length=50),
        ),
        migrations.AddField(
            model_name='bid',
            name='bidder_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bid',
            name='product',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='user.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='categoryname',
            field=models.CharField(default=0.0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='picon',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
